#!/bin/bash

set -e -o pipefail

execute_sinad () {
    samba-tool "$@"
}
clear_holding_stone () {
    # remove config stone.
    rm -f /tmp/holding_stone
}
check_provisioned () {
    # See if there is sam.ldb in /var/lib/samba/private.
    if [ -f /var/lib/samba/private/sam.ldb ]; then
        echo "It seems Sinad is already provisioned."
        read -p 'Do you want to continue to provision it anyway? [y|n] ' YN
        case $YN in
            [Yy]*)
                provision_sinad
                ;;
            *)
                echo Abort provisioning
                ;;
        esac
    else
        provision_sinad
    fi
}
provision_sinad () {
    # Get samba admin password.
    while :
    do
        read -s -p 'Type samba admin password: ' ADMINPW1
        echo
        read -s -p 'Type samba admin password again: ' ADMINPW2
        echo
        if [ x"$ADMINPW1" == x"$ADMINPW2" ]; then
            break
        else
            echo "Passwords are not matched. Try again."
            sleep 0.5
        fi
    done
    # Get realm
    read -p 'Type realm name (eg. iorchard.lan): ' REALM
    # Get domain from realm
    DOMAIN=${REALM%.*}
    # Get Sinad host IP address.
    read -p 'Type Sinad host IP address: ' HOST_IP
    # Backup original config files.
    mv /etc/krb5.conf /etc/krb5.conf.orig
    mv /etc/samba/smb.conf /etc/samba/smb.conf.orig
    # Provision
    samba-tool domain provision --use-rfc2307 --realm=$REALM --domain=$DOMAIN \
        --host-name=$HOSTNAME --host-ip=$HOST_IP --adminpass=$ADMINPW1 \
        --dns-backend=SAMBA_INTERNAL --server-role=dc
    cp /var/lib/samba/private/krb5.conf /etc/
    # Add some lines to smb.conf
    cat <<EOF > /tmp/smb.tmp
# Beginning of additions
        template shell = /bin/bash
        winbind use default domain = true
        winbind offline logon = false
        winbind nss info = rfc2307
        winbind enum users = yes
        winbind enum groups = yes
[users]
	path = /srv/samba/users
	read only = no

[profiles]
	path = /srv/samba/profiles
	read only = no
# End of additions

EOF
    sed -Ei '/idmap_ldb:/r /tmp/smb.tmp' /etc/samba/smb.conf
    # remove stone.
    clear_holding_stone
    sleep 7
    # Change /etc/resolv.conf
    echo -e "search $REALM\nnameserver $HOST_IP" > /etc/resolv.conf
    # Update pam auth
    pam-auth-update --enable mkhomedir unix winbind 2>/dev/null
    # Remove ip address from DNS except $HOST_IP.
    echo "Remove ip addresses from DNS except $HOST_IP."
    set +e
    IP_LIST=($(hostname -I))
    for i in ${IP_LIST[*]}
    do
        if [ x"${i}" != x"${HOST_IP}" ]; then
            samba-tool dns delete $HOSTNAME $REALM $HOSTNAME A $i -U administrator
            samba-tool dns delete $HOSTNAME $REALM $REALM A $i -U administrator
        fi
    done
    set -e
    # Grant SeDiskOperatorPrivilege to BUILTIN\Administrators.
    echo "Grant SeDiskOperatorPrivilege to BUILTIN\Administrators."
    net rpc rights grant "BUILTIN\Administrators" SeDiskOperatorPrivilege \
        -U administrator
    # Create profiles/users folder in /srv/samba
    mkdir -p /srv/samba/{profiles,users}
    chown root:"Domain Admins" /srv/samba/{profiles,users}
    chmod 0770 /srv/samba/{profiles,users}
    reload_sinad
}
ping_sinad () {
    echo -n "smbd: "
    smbcontrol smbd ping
    echo -n "winbindd: "
    smbcontrol winbindd ping
}
run_sinad () {
    while :
    do
        if [ -f /tmp/holding_stone ]; then
            sleep 5
        else
            break
        fi
    done
    /usr/sbin/samba --foreground --no-process-group --debuglevel=5
}
reload_sinad () {
    smbcontrol all reload-config
}
user_sinad () {
    read -p 'Type the userid: ' USERID
    read -p 'Type the user surname: ' SURNAME
    read -p 'Type the user givenname: ' GIVENNAME
    samba-tool user create $USERID \
      --given-name="$GIVENNAME" --surname="$SURNAME" \
      --description="$SURNAME $GIVENNAME account"
    echo "Create $USERID home folder."
    mkdir -p /srv/samba/users/$USERID
    chown 3000000:users /srv/samba/users/$USERID
    # Get DOMAIN
    DOMAIN=$(samba-tool domain info sinad |grep 'Netbios domain' |cut -d ':' -f2 |tr -d '[:space:]')
    # setfacl
    setfacl -x "u:root" /srv/samba/users/$USERID
    setfacl -x "d:u:root" /srv/samba/users/$USERID
    setfacl -m "u:${DOMAIN}\\${USERID}:rwx" /srv/samba/users/$USERID
    setfacl -m "g:BUILTIN\\Administrators:rwx" /srv/samba/users/$USERID
    setfacl -m "g:${DOMAIN}\\${USERID}:rwx" /srv/samba/users/$USERID
    setfacl -m "d:u:3000000:rwx" /srv/samba/users/$USERID
    setfacl -m "d:u:${DOMAIN}\\${USERID}:rwx" /srv/samba/users/$USERID
    setfacl -m "d:g:BUILTIN\\Administrators:rwx" /srv/samba/users/$USERID
    setfacl -m "d:g:${DOMAIN}\\${USERID}:rwx" /srv/samba/users/$USERID
}
USAGE() {
    echo "Usage: $0 {-h|-c|-e|-p|-P|-r|-R|-u}" 1>&2
    echo " "
    echo "  -h  --help          Display this help message."
    echo "  -c  --clear         Clear the holding stone."
    echo "  -e  --execute       Execute command."
    echo "  -p  --provision     Provision Sinad."
    echo "  -P  --ping          Ping Sinad daemons (smbd and winbindd)."
    echo "  -r  --run           Run Sinad."
    echo "  -R  --reload        Reload Sinad config."
    echo "  -u  --user          Create a user."
}

if [ $# -lt 1 ]; then
    USAGE
    exit 0
fi

OPT=$1
shift
# Get argument
while :
do
    case "$OPT" in
        -c | --clear)
            clear_holding_stone
            break
            ;;
        -e | --execute)
            execute_sinad "$@"
            break
            ;;
        -h | --help)
            USAGE
            break
            ;;
        -p | --provision)
            check_provisioned
            break
            ;;
        -P | --ping)
            ping_sinad
            break
            ;;
        -r | --run)
            run_sinad
            break
            ;;
        -R | --reload)
            reload_sinad
            break
            ;;
        -u | --user)
            user_sinad
            break
            ;;
        *)
            echo Error: unknown option: "$OPT" 1>&2
            echo " "
            USAGE
            break
            ;;
    esac
done
